
package com.axiom.lib.image;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class BitmapFormatException extends Exception {

public BitmapFormatException() {
	super();
}

public BitmapFormatException(String s) {
	super(s);
}
}