
package com.axiom.lib.image;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class ReaderFormatException extends Exception {

/**
 * ReaderFormatException constructor comment.
 */
public ReaderFormatException() {
	super();
}
/**
 * ReaderFormatException constructor comment.
 * @param s java.lang.String
 */
public ReaderFormatException(String s) {
	super(s);
}
}